jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Create Clasp Config
        run: |
          cat <<EOF > .clasp.json
          {"scriptId":"${{ secrets.CLASP_SCRIPT_ID }}","rootDir":"src"}
          EOF

      - name: Create Clasp Auth
        run: |
          cat <<EOF > ~/.clasprc.json
          ${{ secrets.CLASPRC_JSON }}
          EOF

      - name: Run Linter
        run: npx eslint src/

      - name: Push to Google
        run: clasp push -f

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: clasp deploy -i "${{ secrets.PROD_DEPLOYMENT_ID }}" -d "Prod Release:${{ github.sha }}"